# Generated by Django 4.0.2 on 2022-02-16 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(blank=True, default='Unnamed User', max_length=30, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, default='Unnamed User', max_length=30, verbose_name='Last name')),
                ('email', models.EmailField(blank=True, default='Email ID', max_length=254, verbose_name='Email ID')),
                ('password', models.CharField(blank=True, default='Password', max_length=40, verbose_name='Password')),
            ],
        ),
    ]
