# Generated by Django 4.0.3 on 2022-03-04 13:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
        ('groups', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('expense_name', models.CharField(max_length=255)),
                ('total_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.user')),
                ('group_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='groups.group')),
            ],
        ),
        migrations.CreateModel(
            name='ExpenseToUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('share', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('initial_amt_paid', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('amt_receive', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('amt_paid', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('outstanding', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('expense_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='expense_user', to='expenses.expense')),
                ('users_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.user')),
            ],
        ),
        migrations.CreateModel(
            name='Debts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amt', models.DecimalField(decimal_places=2, max_digits=10)),
                ('bearer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bearer', to='users.user')),
                ('exp_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='expenses.expense')),
                ('payer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payer', to='users.user')),
            ],
        ),
    ]
