# Generated by Django 4.0.2 on 2022-03-02 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='expensetouser',
            name='amount_owed',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='expensetouser',
            name='is_active',
            field=models.BooleanField(blank=True, default=True),
        ),
        migrations.AddField(
            model_name='expensetouser',
            name='is_settled',
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
