# Generated by Django 4.0.2 on 2022-03-03 09:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_user_last_login_alter_user_password'),
        ('expenses', '0002_expensetouser_amount_owed_expensetouser_is_active_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='expense',
            old_name='payee_id',
            new_name='created_by',
        ),
        migrations.RenameField(
            model_name='expensetouser',
            old_name='amount_owed',
            new_name='amt_paid',
        ),
        migrations.RenameField(
            model_name='expensetouser',
            old_name='amount_paid',
            new_name='amt_receive',
        ),
        migrations.RemoveField(
            model_name='expensetouser',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='expensetouser',
            name='is_settled',
        ),
        migrations.AddField(
            model_name='expensetouser',
            name='initial_amt_paid',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='expensetouser',
            name='outstanding',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='expensetouser',
            name='share',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.CreateModel(
            name='Debts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amt', models.DecimalField(decimal_places=2, max_digits=10)),
                ('bearer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bearer', to='users.user')),
                ('exp_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='expenses.expense')),
                ('payer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payer', to='users.user')),
            ],
        ),
    ]
