# Generated by Django 4.0.3 on 2022-03-07 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0002_debts_group_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='debts',
            name='is_paid',
            field=models.BooleanField(default=False),
        ),
    ]
