# Generated by Django 4.0.3 on 2022-03-04 13:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group_name', models.CharField(blank=True, max_length=45, null=True)),
                ('group_type', models.CharField(choices=[('H', 'HOME'), ('T', 'TRIP'), ('O', 'OTHER')], default='H', max_length=1)),
                ('group_description', models.TextField(blank=True, null=True)),
                ('created_at', models.DateField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.IntegerField(blank=True, null=True)),
                ('created_by', models.ForeignKey(db_column='created_by', on_delete=django.db.models.deletion.CASCADE, to='users.user')),
            ],
            options={
                'ordering': ['group_name'],
                'unique_together': {('group_name', 'created_by')},
            },
        ),
        migrations.CreateModel(
            name='GroupToUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.IntegerField(blank=True, null=True)),
                ('group_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='groups.group')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.user')),
            ],
            options={
                'unique_together': {('group_id', 'user_id')},
            },
        ),
    ]
